export const ActionType = {
    FETCH_PRODUCTS : "FETCH_PRODUCTS",
    SET_PRODUCT : "SET_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    FETCH_SELECTED_PRODUCTS : "FETCH_SELECTED_PRODUCTS",
    ADD_TWO_NUMBER : "ADD_TWO_NUMBER"
}